name: '$(Date:yyyyMMdd).$(Rev:rr)'

trigger: none
  #branches:
  #  include:
  #  - 'main'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vg-all
- group: vg-security
- group: vg-prod
- name: 'AzureServiceConnection'
  value: 'sc-prod'

stages:
- template: templates/stage-deploy-infra.yaml
