name: '$(Date:yyyyMMdd).$(Rev:rr)'

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vg-all
- group: vg-test
- name: 'AzureServiceConnection'
  value: 'sc-test'

stages:
- template: templates/stage-destroy-infra.yaml
