parameters:
  DependsOn: []

jobs:
- job: deployFoundation
  strategy:
    matrix: $[ variables['AzureLocations'] ]
  displayName: "Deploy Foundation:"
  dependsOn: ${{ parameters.DependsOn }}
  steps:
    - checkout: self

    - template: step-set-azure-cli.yaml

    - template: step-set-variables.yaml

    #- template: step-deploy-resource-groups.yaml

    #- template: step-deploy-log-analytics-workspace.yaml

    #- template: step-deploy-subscription-diagnostics.yaml

    #- template: step-deploy-user-assigned-identity.yaml

    #- template: step-set-variables-user-assigned-identity.yaml

    #- template: step-deploy-role-assignments-sub.yaml
