stages:
- stage: destroy
  jobs:
  - job: destroyInfrastructure
    strategy:
      matrix: $[ variables['AzureLocations'] ]
    displayName: "Destroy Infrastructure: "
    steps:
      - checkout: self
      - checkout: git://PipelineTemplates/Utilities

      - template: step-set-azure-cli.yaml

      - task: Powershell@2
        displayName: "Install Azure Powershell modules"
        inputs:
          targetType: inline
          script: |
            Install-Module -Name "Az.Accounts" -Force -AllowClobber -Scope CurrentUser

      - task: Powershell@2
        displayName: "Download plzm.Azure module"
        inputs:
          targetType: inline
          script: |
            . ./azure-pipelines-poc/scripts/Module.ps1
            Get-PlzmAzureModule -UrlRoot $(UriPs1ModulePlzmAzure)

      - template: step-set-variables.yaml

      - template: step-set-variables-user-assigned-identity.yaml
        parameters:
          ResourceGroupName: $(RgNameMain)
          UaiName: $(UaiName)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: Workload RG'
          ResourceGroupName: $(RgNameWorkload)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: Network RG'
          ResourceGroupName: $(RgNameNetwork)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: Main RG'
          ResourceGroupName: $(RgNameMain)

      - template: step-delete-role-assignments-sub.yaml

      - template: step-delete-resource-groups.yaml
