stages:
- stage: deploy
  jobs:
  # deployPrerequisites
  - template: job-deploy-prerequisites.yaml

  # deployFoundation
  - template: job-deploy-foundation.yaml
    parameters:
      DependsOn:
      - deployPrerequisites
