stages:
- stage: deploy
  jobs:
  # deployPrerequisites
  - template: job-deploy-prerequisites.yaml

  # deployFoundation
  - template: job-deploy-foundation.yaml
    parameters:
      DependsOn:
      - deployPrerequisites

  ## deployNetwork
  #- template: job-deploy-network.yaml
  #  parameters:
  #    DependsOn:
  #    - deployFoundation

  ## deployWorkload
  #- template: job-deploy-workload.yaml
  #  parameters:
  #    DependsOn:
  #    - deployNetwork
