stages:
- stage: destroy
  jobs:
  - job: destroyInfrastructure
    strategy:
      matrix: $[ variables['AzureLocations'] ]
    displayName: "Destroy Infrastructure: "
    steps:
      - checkout: self
      - checkout: git://PipelineTemplates/Utilities

      - template: step-set-azure-cli.yaml

      - template: step-set-variables.yaml

      - template: step-set-variables-user-assigned-identity.yaml
        parameters:
          ResourceGroupName: $(RgNameMain)
          UaiName: $(UaiName)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: $(RgNameWorkload)'
          ResourceGroupName: $(RgNameWorkload)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: $(RgNameNetwork)'
          ResourceGroupName: $(RgNameNetwork)

      - template: step-delete-diagnostics-settings.yaml
        parameters:
          TaskName: 'Destroy Diagnostics Settings: $(RgNameMain)'
          ResourceGroupName: $(RgNameMain)

      - template: step-delete-role-assignments-sub.yaml

      - template: step-delete-resource-groups.yaml
